version: 1
inputs:
  - name: 'IO board input'
    address: 2187
    access: read
    value_type: word
    length: 10

  - name: 'IO board output'
    address: 2227
    access: read_write
    value_type: word
    length: 10

  - name: 'Mode'
    address: 2185
    access: read
    value_type: word
    length: 1

  - name: 'Movement status'
    address: 2470
    access: read
    value_type: word
    length: 1
    
  - name: 'World position'
    address: 2332
    access: read
    value_type: word
    length: 16

  - name: 'Alarm status'
    address: 2396
    access: read
    value_type: word
    length: 1

  - name: 'Activate button'
    address: 20003
    access: write
    value_type: word
    length: 1

  - name: 'Stop button'
    address: 20004
    access: write
    value_type: word
    length: 1

  - name: 'Start'
    address: 160
    access: read_write
    value_type: bit
    length: 1
